---
stages:
- name: Build flow
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build driver
    type: builder
    artifact_dir: target
    build_type: maven
    script: |-
      #!/bin/bash
      export JAVA_HOME=$JAVA8_HOME
      mvn -B -Pstreams-runner package
- name: Deploy flow to development
  inputs:
  - type: job
    stage: Build flow
    job: Build driver
  triggers:
  - type: stage
  properties:
  - name: streaming_analytics_credentials
    value: "test"
    type: text_area
  - name: PIPELINE_API_KEY
    value: ${API_KEY}
    type: text
  - name: DEV_SPACE
    value: ${dev-space}
    type: text
  jobs:
  - name: Deploy flow
    type: deployer
    deploy_type: customimage
    script: |
      #!/bin/bash

      echo "dump apikey and env"
      echo "P_API_KEY: $PIPELINE_API_KEY"
      export A_API_KEY={{API_KEY}}
      export
      echo "API_KEY: A_API_KEY"
      env

      echo "generating vcap.json"
      echo "{
        \"streaming-analytics\":[{
          \"name\" : \"streaming-analytics\",
          \"credentials\" : $streaming_analytics_credentials
        }]
      }" > vcap.json

      java -cp ./example-starter-kit-0.1-SNAPSHOT.jar:./dependency/com.ibm.streams.beam-1.2.1/com.ibm.streams.beam/lib/com.ibm.streams.beam.translation.jar \
      com.ibm.streams.beam.sample.temperature.TemperatureSample \
      --runner=StreamsRunner \
      --contextType=STREAMING_ANALYTICS_SERVICE \
      --vcapServices=./vcap.json \
      --serviceName=streaming-analytics \
      --beamToolkitDir=./dependency/com.ibm.streams.beam-1.2.1 \
      --jarsToStage=./example-starter-kit-0.1-SNAPSHOT.jar \
      --jobName={{name}}
    docker_image: maven:3.5.3-ibmjava
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: http://lms-api/v1/messaging/webhook/publish
