version: '2'
template:
  name: Continuous Delivery Toolchain
  description: "This toolchain includes tools to develop and deploy your event driven app. \n\nThis toolchain uses tools that are part of the Continuous Delivery service. If an instance of that service isn't already in your organization, when you click **Create**, it is automatically added at no cost to you. For more information and terms, see the [IBM Cloud catalog](/catalog/services/continuous-delivery/).\n\nTo get started, click **Create**."
  required:
    - repo
    - build

toolchain:
  name: MyFirstGeneratedApplication

services:
  # Github repos
  repo:
    service_id: hostedgit
    parameters:
      repo_url: "{{#zip_url}}{{zip_url}}{{/zip_url}}{{^zip_url}}{{repository}}{{/zip_url}}"
      repo_name: "{{toolchain.name}}"
      type: clone
      has_issues: true
      enable_traceability: true

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: "{{name}}"
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP: "{{form.pipeline.parameters.app-name}}"
          API_KEY: "{{form.pipeline.parameters.api-key}}"
          CF_SPACE: "{{form.pipeline.parameters.dev-space}}"
          CF_ORGANIZATION: "{{form.pipeline.parameters.dev-organization}}"
          REGION_ID: "{{form.pipeline.parameters.dev-region}}"
        execute: true

  #Web IDE
  webide:
    service_id: orion

#Deployment
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      app-name: Mbladafsdfasdfy
      api-key: "Mbladafsdfasdfy"
      dev-region: "Mbladafsdfasdfy"
      dev-space: "Mbladafsdfasdfy"
      dev-organization: "bladafsdfasdfy"
